### ISSUE TITLE
Gradle related settings

### ISSUE THREAD

**Issue by khalid-hussain** [JaySoyer/Advanced-Adapters#52]
Hi there,

I have come from [StackOverflow](http://stackoverflow.com/questions/27622039/listview-search-widget-filter?noredirect=1#comment43665961_27622039) and have been trying for a while to import the project into Android Studio 1.0. I've been having a lot of trouble importing this "out of the box".

Most of the issues have to do with Gradle. I'm not an expert at this but updating these settings would help others easily import the project.

Some things to look out for:
1) ApplicationId entry in the build.gradle file.
2) Settings relating to the proGuard in the build.gradle file.
3) Updating the gradle plugin version.

The latest error I'm trying to solve is:
```
Error:Execution failed for task ':lib:proguardRelease'.
> java.io.FileNotFoundException: C:\Users\Khalid\AndroidStudioProjects\Advanced-Adapters-master\lib\proguard-rules.txt (The system cannot find the file specified)
```

Thanks for the hard work you have put in.

**Comment by JaySoyer** [comment]
Thanx for the heads up!  Will get a solution back to you NTL end of day tomorrow.  As side note, I'm planning on getting this guy up on Maven in a few months to hopefully avoid these problems.

**Comment by JaySoyer** [comment]
Looks like the problem was that the master branch was built using the alpha builds of Android Studio.  As a result it was using a now invalid gradle version.  I've updated the master branch and wrote a [Getting Started](https://github.com/JaySoyer/Advanced-Adapters/wiki/Getting-Started) wiki page to for detailed instructions with trouble shooting procedures.

Go a head and pull in the new changes, re-import the module and see if it fixes your problems.

**Comment by khalid-hussain** [comment]
That did it. Thanks.
